config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'main#index'
  
  resources :quizzes 
    
  
  resources :users
  
  get '/index' => 'main#index'
  
  get '/profile' => 'users#profile'
  get '/signup' => 'users#new'
  get '/my_random' => 'users#myrandom'
  get '/my_quizzes' => 'users#myquizzes'
  
  get '/normal' => 'quizzes#normal'
  
  get '/random/:index' => 'quizzes#random', :as => :random_with_index
  post '/random/:index/check' => 'quizzes#checkanswer_random'
  get '/random/:index/wrong' => 'quizzes#randomwronganswer'
  get '/random/:index/right' => 'quizzes#randomrightanswer'
  get '/random/:index/answer' => 'quizzes#randomquizanswer'
  get '/result' => 'quizzes#randomresult'
  post 'quizzes/:quiz_id/like' => 'quizzes#like_toggle'
  post 'quizzes/:quiz_id/check' => 'quizzes#checkanswer'
  
  get 'quizzes/:quiz_id/answer' => 'quizzes#quizanswer'
  get 'quizzes/:quiz_id/right' => 'quizzes#rightanswer'
  get 'quizzes/:quiz_id/wrong' => 'quizzes#wronganswer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    belongs_to :user
    
    before_destroy { |quiz| quiz.likes.destroy }
    
    def next
        self.class.where("id > ?", id).first
    end
    
    def previous
        self.class.where("id < ?", id).last
    end
    
    validates :answer,
        presence: true,
        length: { minimum: 1 }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :likes
    has_many :liked_posts, through: :likes, source: :quiz
    
    def is_like?(quiz)
        Like.find_by(user_id: self.id, quiz_id: quiz.id).present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  include SessionsHelper

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
 
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    $quizzes = Quiz.order(Arel.sql('RANDOM()')).first(10)
    $score = 0
    
    
    def normal
        @quiz = Quiz.first
        @quizzes = Quiz.all
        
        @category = Quiz.distinct.pluck(:Category)
    end
    
    def random
        @quiz = $quizzes[params[:index].to_i]
        @index = params[:index].to_i
        
        if @index > 9
            redirect_to result_path
        end
    end
    
    def randomresult
        if session[:random].nil?
            session[:random] = $score
        else
            session[:random] += $score
        end
        
        @score = $score
        $quizzes = Quiz.order(Arel.sql('RANDOM()')).first(10)
        $score = 0
    end
    
    def like_toggle
        like = Like.find_by(user_id: current_user.id, quiz_id: params[:quiz_id])
        
        if like.nil?
            @like = Like.create(user_id: current_user.id, quiz_id: params[:quiz_id])
        else
            like.destroy
        end
        
        redirect_to :back
    end
    
    def checkanswer
        if params[:answer].gsub(/\s+/, "").downcase == Quiz.find(params[:quiz_id]).answer.gsub(/\s+/, "").downcase
            redirect_to '/quizzes/' + params[:quiz_id] + '/right'
        else
            redirect_to '/quizzes/' + params[:quiz_id] + '/wrong'
        end
    end
    
    def checkanswer_random
        if params[:answer].gsub(/\s+/, "") == $quizzes[params[:index].to_i].answer.gsub(/\s+/, "")
            redirect_to '/random/' + params[:index] + '/right'
        else
            redirect_to '/random/'+ params[:index] + '/wrong'
        end
    end
    
    def randomrightanswer
        @quiz = $quizzes[params[:index].to_i]
        @index = params[:index].to_i
        if $score >= 10
            $score = 10
        else
            $score += 1
        end
    end
    
    def randomwronganswer
        @quiz = $quizzes[params[:index].to_i] 
        @index = params[:index].to_i
        
    end
    
    def rightanswer
        @quiz = Quiz.find(params[:quiz_id]) 
        @nextquiz = @quiz.next
        @quizzes = Quiz.all
    end
    
    def wronganswer
        @quiz = Quiz.find(params[:quiz_id]) 
        @quizzes = Quiz.all
    end
    
    def quizanswer
        @quiz = Quiz.find(params[:quiz_id]) 
        @nextquiz = @quiz.next
        @quizzes = Quiz.all 
    end
    
    def randomquizanswer
        @quiz = $quizzes[params[:index].to_i] 
        @index = params[:index].to_i
    end
    
    def new
        @quiz = Quiz.new
    end
    
    def edit
        @quiz = Quiz.find(params[:id])
    end
    
    def update
        @quiz = Quiz.find(params[:id])
        
        if @quiz.update(quiz_params)
            redirect_to @quiz
        else
            render 'edit'
        end
    end
    
    def create
        @quiz = Quiz.new(quiz_params)
        @quiz.user = current_user
        
        if @quiz.save
            redirect_to @quiz
        else
            render 'new'
        end
    end
    
    def destroy
        @quiz = Quiz.find(params[:id])
        @quiz.destroy
        
        redirect_to normal_path
    end
    
    def show
        @quiz = Quiz.find(params[:id])
        @quizzes = Quiz.all
    end
    
private
    def quiz_params
        params.require(:quiz).permit(:answer, :Category, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if is_loggedin
      redirect_to '/'
    end
  end
  
  def create
    
    
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password])
      log_in(@user)
      redirect_to '/'
    else
      flash.now[:danger] = 'invalid login'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
        user = User.new(email: params[:email],
        password: params[:password],
        password_confirmation: params[:password_confirmation])
        user.save!
        redirect_to index_path
    end
    
    def profile
        @user = current_user
        if session[:random].nil?
            @score = 0
        else
            @score = session[:random]
        end
    end
    
    def myrandom
        @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] =user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def is_loggedin
        !current_user.nil?
    end
        
    def log_out
        session.delete(:user_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmojiQuiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset='utf-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    <meta name='description' content='세상의 모든 이모지 퀴즈' />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link
      href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,700&display=swap"
      rel="stylesheet"
      type="text/css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>

  <body class='<%= controller.controller_name %>'>
    <header id="1">

    <nav>
      <% if is_loggedin %>
      
      <div class='row'>
        <ul class='main-nav'>
          <li><%= link_to "Home", index_path %></li>
          <li><%= link_to "일반 퀴즈", normal_path  %></li>
          <li><%= link_to "랜덤 퀴즈", random_with_index_path(:index => 0) %></li>
          <li><%= link_to "로그아웃", logout_path, method: 'delete' %></li>
        </ul>
      </div>
      <%else%>
      
      <div class='row'>
        <ul class='main-nav'>
          <li><%= link_to "Home", login_path %></li>
          <li><%= link_to "일반 퀴즈", login_path  %></li>
          <li><%= link_to "랜덤 퀴즈", login_path %></li>
          <li><%= link_to "로그인", login_path %></li>
        </ul>
      </div>
      
      <%end%>
    </nav>
    <%= yield %>

  
  </header>
  </body>
</html>

app/views/main/index.html.erb
<div class="hero-text-box row">
      <h1>😆이모지 퀴즈📋</h1>
      <h4>
        인터넷 여기저기 흩뿌려진✨ <br />이모지 퀴즈들, 여기 다 모았다! 🤪
      </h4>
</div>
    <% if is_loggedin %>
      <div class="quiz-kind-box row js--ani-1">
        <%= link_to normal_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">🎨</div>
          <h3>일반 퀴즈</h3>
          <p>
            카테고리별로 모아둔<br />
            일반 퀴즈 모음!👉
          </p>
        </div>
        <%end%>
      
      
        <%= link_to random_with_index_path(:index => 0) do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">🤪</div>
          <h3>랜덤 퀴즈</h3>
          <p>
            상상 그 이상의 퀴즈들로<br />
            💯점에 도전해보자!
          </p>
        </div>
        <%end%>
      
        <%= link_to profile_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">👣</div>
          <h3>내 프로필</h3>
          <p>
            내 프로필을 만들고<br />
            📑퀴즈 기록을 남기세요!
          </p>
        </div>
        <%end%>
      </div>
    <%else%>
      <div class="quiz-kind-box row js--ani-1">
        <%= link_to login_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">🎨</div>
          <h3>일반 퀴즈</h3>
          <p>
            카테고리별로 모아둔<br />
            일반 퀴즈 모음!👉
          </p>
        </div>
        <%end%>
      
      
        <%= link_to login_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">🤪</div>
          <h3>랜덤 퀴즈</h3>
          <p>
            상상 그 이상의 퀴즈들로<br />
            💯점에 도전해보자!
          </p>
        </div>
        <%end%>
      
        <%= link_to login_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">👣</div>
          <h3>내 프로필</h3>
          <p>
            내 프로필을 만들고<br />
            📑퀴즈 기록을 남기세요!
          </p>
        </div>
        <%end%>
      </div>
    <%end%>

app/views/quizzes/_answer.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
            <div class = "like_button">
                <%= render 'icons' %>
            </div>
          <p><strong>주제</strong> <%= @quiz.Category %></p>
          <div class="quizRight">
            <h5><%= @quiz.content%></h5>
            <h5><%= @quiz.answer%></h5>
          </div>
          <div class="quizRightOrWrong js--ani-3">
            <h5>정답입니다!</h5>
          </div>
          <a class="btn btn-share" href="#">
            퀴즈 공유하기
          </a>
          <a class="btn btn-full" href="/quizzes/<%= @nextquiz.id %>">
            다음 문제
          </a>
        </div>
      </div>
</div>

app/views/quizzes/_form.html.erb
<%= form_for :quiz, url: quizzes_path do |f| %>
    <% if @quiz.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@quiz.errors.count, "error") %> prohibited
                this Quiz from being saved:
            </h2>
            <ul>
                <% @quiz.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :answer %><br>
        <%= f.text_field :answer %>
    </p>
    <p>
        <%= f.label :content %><br>
        <%= f.text_area :content %>
    </p>
    <p>
        <%= f.label :Category %><br>
        <%= f.text_area :Category %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/quizzes/_icons.html.erb
<%= link_to index_path do %><i class="icon-left ion-md-arrow-back"></i><%end%>
<% if current_user.is_like? (@quiz) %>
        <form action='/quizzes/<%= @quiz.id%>/like' method='post'>
            <button><span class="fa fa-heart like-btn-unlike"></span></button> 
        </form>
             
        <% else %>
        <form action='/quizzes/<%= @quiz.id%>/like' method='post'>
            <button><span class="fa fa-heart like-btn"></span></button>
        </form>
<% end %>

app/views/quizzes/_quizlist.html.erb
        <% @quizzes.each do |q| %>
            <li><%= link_to q.content, quiz_path(q) %></li>
        <% end %>

app/views/quizzes/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', normal_path %>

app/views/quizzes/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', normal_path %>

app/views/quizzes/normal.html.erb
<div class="row">
            <div class="quizSolve">
                <div class="col span-2-of-3">
                     <div class = "like_button">
                         <%= render 'icons' %>
                     </div>
                    
                    <p><strong>주제</strong> <%= @quiz.Category %></p>
                    <div class="actualQuiz js--ani-2">
                        <p><%= @quiz.content %></p>
                    </div>
                    <form action='/quizzes/<%= @quiz.id%>/check' method='post'>
                        <input type="text" name="answer" id="answer" placeholder="정답 입력하기" required>
                        <input class="btn btn-full"  type="submit" value="정답 확인하기" id="answerButton">
                    </form>
                </div>
            </div>
            <div class="quizList">
                <div class="col span-1-of-3">
                    <select name="category" id="category">
                        <% @category.each do |c| %>
                            <option value=<%= c %>><%= c %></option>
                        <%end%>
                    </select>
                    <select name="sort" id="sort">
                        <option value="latest" selected>최신순</option>
                        <option value="popularity">인기순</option>
                        <option value="difficult">어려운 문제순</option>
                        <option value="easy">쉬운 문제순</option>
                    </select>
                    <div class="list-wrapper">
                        <ul>
                            <% @quizzes.each do |q| %>
                            
                            <li><%= link_to q.content, quiz_path(q) %></li>
                            <% end %>
                        </ul>
                    </div>
                        
                </div>
            </div>
</div>

app/views/quizzes/random.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
          <div class = "like_button">
            <%= render 'icons' %>
          </div>
          <p><strong>주제</strong> <%= @quiz.Category %>
          <div class="actualQuiz js--ani-2">
            <p><%= @quiz.content %></p>
          </div>
          <form action='/random/<%= @index %>/check' method='post'>
            <input type="hidden" name = "quiz_id", id ="quiz_id" value=<%= @quiz.id%>>
            <input type="text" name="answer" id="answer" placeholder="정답 입력하기" required>
            <input class="btn btn-half"  type="submit" value="정답 확인하기" id="answerButtonRandom">
          <a class="btn btn-half" href="/random/<%= @index+1 %>">
            패스하기
          </a>
          </form>
        </div>
      </div>
      <div class="scoreBoard">
        <p>🤪점수표📋</p>
        <!--<div class="right-wrong">-->
          
        <!--  ⭕❌❌❌❌❌❌❌❌❌-->
          
        <!--</div>-->
        <div class="actualScore">
          <h1><%= $score*10 %></h1>
          <p>/100점</p>
        </div>
      </div>
</div>

app/views/quizzes/randomquizanswer.html.erb
<div class="row">
            <div class="quizSolve">
                <div class="col span-2-of-3">
                    <div class = "like_button">
                         <%= render 'icons' %>
                     </div>
                    <p><strong>주제</strong> <%= @quiz.Category%></p>
                    <div class="quizAnswerHere">
                        <h5>정답 공개!</h5>
                    </div>
                    <div class="quizAnswer">
                        <h5><%= @quiz.content %><h5>
                        <h5><%= @quiz.answer %></h5>
                    </div>
                    <a class="btn btn-share" href="#">
                        퀴즈 공유하기
                    </a>
                    <a class="btn btn-full" href="/random/<%= @index+1 %>">
                        다음 문제
                    </a>
                </div>
            </div>
</div>

app/views/quizzes/randomresult.html.erb
    <div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
          <a href="index.html"><i class="icon-left ion-md-arrow-back"></i></a>
          <p>랜덤퀴즈 결과</p>
          <div class="quizWrong">
            <h5>퀴즈 결과: <%= @score*10 %>/100 점</h5>
            <h6>아주 좋습니다!</h6>
          </div>
          <a class="btn btn-share" href="#">
            퀴즈 공유하기
          </a>
          <a class="btn btn-full" href="/random/0">
            다른 랜덤퀴즈 풀기
          </a>
        </div>
      </div>
    </div>

app/views/quizzes/randomrightanswer.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
            <div class = "like_button">
                <%= render 'icons' %>
            </div>
          <p><strong>주제</strong> <%= @quiz.Category %></p>
          <div class="quizRight">
            <h5><%= @quiz.content%></h5>
            <h5><%= @quiz.answer%></h5>
          </div>
          <div class="quizRightOrWrong js--ani-3">
            <h5>정답입니다!</h5>
          </div>
          <a class="btn btn-share" href="#">
            퀴즈 공유하기
          </a>
          <a class="btn btn-full" href="/random/<%= @index+1 %>" >
            다음 문제
          </a>
        </div>
      </div>
</div>

app/views/quizzes/randomwronganswer.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
          <div class = "like_button">
                 <%= render 'icons' %>
            </div>
          <p><strong>주제</strong> <%= @quiz.Category %></p>
          <div class="quizWrong">
            <p><%= @quiz.content %><p>
          </div>
          <div class="quizRightOrWrong js--ani-4">
            <h5>오답입니다</h5>
          </div>
          <a class="btn btn-share" href="#">
            퀴즈 공유하기
          </a>
          
          <a class="btn btn-half" href="/random/<%= @index %>/answer">
            정답 보기
          </a>
          
          <a class="btn btn-half" href= "/random/<%= @index %>">
            다시 풀기
          </a>
          
        </div>
      </div>
      
</div>

app/views/quizzes/rightanswer.html.erb
    <div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
            <div class = "like_button">
                <%= render 'icons' %>
            </div>
          <p><strong>주제</strong> <%= @quiz.Category %></p>
          <div class="quizRight">
            <h5><%= @quiz.content%></h5>
            <h5><%= @quiz.answer%></h5>
          </div>
          <div class="quizRightOrWrong js--ani-3">
            <h5>정답입니다!</h5>
          </div>
          <a class="btn btn-share" href="#">
            퀴즈 공유하기
          </a>
          <a class="btn btn-full" href="/quizzes/<%= @nextquiz.id %>">
            다음 문제
          </a>
        </div>
      </div>
      <div class="quizList">
        <div class="col span-1-of-3">
          <select name="category" id="category">
            <option value="movie" selected>영화</option>
            <option value="music">음악</option>
            <option value="novel">소설</option>
            <option value="webtoon">웹툰</option>
            <option value="musical">뮤지컬</option>
          </select>
          <select name="sort" id="sort">
            <option value="latest" selected>최신순</option>
            <option value="popularity">인기순</option>
            <option value="difficult">어려운 문제순</option>
            <option value="easy">쉬운 문제순</option>
          </select>
          <div class="list-wrapper">
            <ul>
                <% @quizzes.each do |q| %>
                <li><%= link_to q.content, quiz_path(q) %></li>
                <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/quizzes/show.html.erb
<div class="row">
            <div class="quizSolve">
                <div class="col span-2-of-3">
                     <div class = "like_button">
                         <%= render 'icons' %>
                     </div>
                    
                    <p><strong>주제</strong> <%= @quiz.Category %></p>
                    <div class="actualQuiz js--ani-2">
                        <p><%= @quiz.content %></p>
                    </div>
                    <form action='/quizzes/<%= @quiz.id%>/check' method='post'>
                        <input type="text" name="answer" id="answer" placeholder="정답 입력하기" required>
                        <input class="btn btn-full"  type="submit" value="정답 확인하기" id="answerButton">
                    </form>
                </div>
            </div>
            <div class="quizList">
                <div class="col span-1-of-3">
                    <select name="category" id="category">
                        <option value="movie" selected>영화</option>
                        <option value="music">음악</option>
                        <option value="novel">소설</option>
                        <option value="webtoon">웹툰</option>
                        <option value="musical">뮤지컬</option>
                    </select>
                    <select name="sort" id="sort">
                        <option value="latest" selected>최신순</option>
                        <option value="popularity">인기순</option>
                        <option value="difficult">어려운 문제순</option>
                        <option value="easy">쉬운 문제순</option>
                    </select>
                    <div class="list-wrapper">
                        <ul>
                            <% @quizzes.each do |q| %>
                            <li><%= link_to q.content, quiz_path(q) %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
</div>

app/views/users/myrandom.html.erb
<% @user.likes.each do |q| %>
    <%= q.quiz.answer %><br>
    <%= q.quiz.content %><br>
<%end%>

app/views/users/new.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
          <%= link_to index_path do %><i class="icon-left ion-md-arrow-back"></i><%end%>
          <p>가입하기</p>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="explain-form">
        <p>이메일로 가입하기</p>
      </div>
      
      <%= form_tag '/users' do %>
        <input type="email" name="email" placeholder="이메일"><br>
        <input type="password" name="password" placeholder="패스워드"><br>
        <input type="password" name="password_confirmation" placeholder="패스워드 확인"><br>
        <input type="submit" value="회원가입">
      <% end %>
    </div>
    

app/views/users/profile.html.erb
<div class="row">
      <div class="quizSolve">
        <div class="col span-2-of-3">
          <a href="index.html"><i class="icon-left ion-md-arrow-back"></i></a>
          <i class="icon-right ion-md-share"></i>
          <p>내 프로필</p>
        </div>
      </div>
    </div>

    <div class="quiz-kind-box">
        <div class="options col span-1-of-3">
          <div class="emoji-icon">😀</div>
          <h3>타이틀: 퀴즈 뉴비</h3>
          <p>
            퀴즈를 더 많이 풀고 <br />
            등급을 올려보세요!
          </p>
        </div>
        <div class="row">
            <p><strong>다음 타이틀</strong> 퀴즈 쌉고수</p>
            <p><strong>누적 점수</strong> <%= @score*10 %></p>
        </div>
      <div class="row"><progress value="40" max="100"></progress></div>
      <%= link_to my_quizzes_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">📑</div>
          <h3>풀었던 퀴즈들</h3>
          <p>
            내가 풀었던 <strong>42</strong>개의<br />
            퀴즈들을 다시 풀어보자!
          </p>
        </div>
      <%end%>
      <%= link_to my_random_path do %>
        <div class="options col span-1-of-3">
          <div class="emoji-icon">💕</div>
          <h3>좋아요 퀴즈들</h3>
          <p>
            내가 좋아요를 눌렀던 <strong><%= current_user.likes.size %></strong>개의<br />
            퀴즈들을 다시 풀어보자!
          </p>
        </div>
      <%end%>
    </div>